#!/bin/sh

# Getting the current branch
currentBranch=$(git symbolic-ref --short -q HEAD)
# Seeing if default branch is master or main
mainBranch=$(git branch | grep -o -m1 '\b\(master\|main\)\b')
git checkout $mainBranch
git pull
git branch -D $currentBranch
